<div class="row">
    <h3 class="ml-3 mt-3 mb-5" >More information about NANA</h3>
</div>

<div class="card ">

    <div class="card-header bg-primary ">
        <h5 class="card-title text-light">Data flow from the network to the user</h5>
    </div>
    <div class="card-text p-3">
        <ul>
            <p>
            <li>ARP and ND records are collected by sensors (pcap listeners) 
                and visible for the user in seconds (software sensors should be run on every L3 network you want to track)
            </li>
            </p>
            <p>         
            <li>
                SNMP counters are periodically read and stored into RRD, other variables go to MySQL
            </li>
            </p>
            <p>
            <li>
                other processing is done asynchronously to balance between data need and useless load
            </li>
            </p>
        </ul>

        <img src="<?= $this->basePath() . '/img/nana_data_flow.png' ?>">
    </div>

</div>

<div class="card mt-5 ">

    <div class="card-header bg-primary ">
        <h5 class="card-title text-light">Scalability</h5>
    </div>
    <div class="card-text p-3">



        <p>
            Nana can be run on one or more physical or virtual machines.<br/>
            It's possible only to scatter the sensors on the network and use nana remotely in the cloud (off the network)
        </p>

        </ul>
        My current setup (all on the CentOS Linux):

        <ul>
            <li>
                VM for core
            </li>

            <li>
                VM for MySQL database
            </li>

            <li>
                NFS server with SSD for RRD files
            </li>

            <li>
                web server for PHP frontend
            </li>

            <li>
                70 sensors on the routers
            </li>
        </ul>
    </div>
</div>


<div class="card mt-5 ">
    <div class="card-header bg-primary ">
        <h5 class="card-title text-light">Used together with</h5>
    </div>
    <div class="card-text p-3">
        <p>
            <a href="https://github.com/balleman/netmrg">NetMRG</a> - to graph various non-counter SNMP data from nana MySQL tables <br/>
            <a href="https://github.com/gamelinux/passivedns">PassiveDNS</a>
        </p>
    </div>
</div>



