<div class="row">
    <h3 class="ml-3 mt-3 mb-5" >NANA</h3>
</div>

<div class="card " style="width: 40rem;">

    <div class="card-header bg-primary ">
        <h5 class="card-title text-light">Download</h5>
    </div>
    <div class="card-text pt-3">
        <table class="table">
            <tr>
                <td>
                    <a href="<?=$this->basePath('download_file/ChangeLog')?>">changelog</a>
                </td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>
                    <a href="<?=$this->basePath('download_file/nana-0.4.2.tgz')?>">nana-0.4.2.tgz</a>
                </td>
                <td>
                    2017-09-09
                </td>
                <td>
                    99 KB
                </td>
                <td>
                    <a href="<?=$this->basePath('download_file/nana-0.4.2.tgz.sha256')?>">sum</a>
                </td>
            </tr>

            <tr>
                <td>
                    <a href="<?=$this->basePath('download_file/nana-0.4.1.tgz')?>">nana-0.4.1.tgz</a>
                </td>
                <td>
                    2016-09-01
                </td>
                <td>
                    75 KB
                </td>
                <td>
                    <a href="<?=$this->basePath('download_file/nana-0.4.1.tgz.sha256')?>">sum</a>
                </td>
            </tr>
        </table>
    </div>

</div>


<div class="card mt-5" style="width: 40rem;">

    <div class="card-header bg-primary ">
        <h5 class="card-title text-light">Git repository</h5>
    </div>
    <div class="card-text pt-3 p-3">
       git clone <a href="https://nanynka.org/nana.git">https://nanynka.org/nana.git</a>
    </div>

</div>