<div class="jumbotron">
    <h1>Welcome to <span class="m-blue">NANA - network analyzer</span></h1>

    <p>
        The network address database and viewer!
    </p>
</div>

<div class="card ">

    <div class="card-header bg-primary ">
        <h4 class="card-title text-light">Design</h4>
    </div>
    <div class="card-text pt-3">
        <ul>
            <li>Live view into the network</li>
            <li>Parallelized and scalable engine</li>
            <li>Maintenance free (setup once, use forever)</li>
        </ul>
    </div>

</div>


<div class="card mt-5 ">

    <div class="card-header bg-primary ">
        <h4 class="card-title text-light">Features</h4>
    </div>

    <div class="card-body pt-3">

        <div class="row">
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">MAC,<br/> IPv4 and IPv6 addreses</h4>
                    </div>
                    <div class="panel-body">
                        <p>
                            ARP and ND tables in database
                        </p>

                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">Searchable by web frontend</h4>
                    </div>
                    <div class="panel-body">
                        <p>
                            All devices are searchable by web frontend
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">Basic SNMP capabilities</h4>
                    </div>
                    <div class="panel-body">
                        <p>
                            MIB-2 - system, interfaces, dot1dBridge, ifXTable
                        </p>
                        <p>
                            Enterprises - 3Com, APC, Cisco, MikroTik, Telindus
                        </p>
                    </div>
                </div>
            </div>
        </div>
        
        
        
        
        <div class="row">
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">Asynchronous DNS reverse resolver</h4>
                    </div>
                    <div class="panel-body">
                        <p>
                            
                        </p>

                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">L2 network topology</h4>
                    </div>
                    <div class="panel-body">
                        <p>
                            L2 network topology discovery based on FDB from Bridge MIB
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"></h4>
                    </div>
                    <div class="panel-body">
                        <p>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>




