<div class="card ">

    <div class="card-header bg-primary ">
        <h5 class="card-title text-light">Todo</h5>
    </div>
    <div class="card-text p-3">
        <p>
            <strong>new release</strong><br/>
            Polish install skripts to make update easier<br/>
            <br/>

            <strong> web frontend </strong><br/>
            Add a vendor to the MAC address page<br/>
            input form for start and end of graph data<br/>
            <br/>

            <strong>SNMP</strong>
            optimize fdb2graph<br/>
            add support for entity MIB<br/>
        </p>

    </div>

</div>
